'use strict';
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=process.env.PORT||3000,PUBLIC=path.join(__dirname,'public'),uid=()=>crypto.randomBytes(12).toString('hex');
const players=new Map(),playerStreams=new Map(),hostStreams=new Set();
let generation=uid(),round={id:0,active:false,mode:'reflex',duration:7,practice:false},view={mode:'reflex',duration:7},roundResponses=new Set();
let uniqueGame={status:'idle',answers:new Map(),result:null,practice:false};
let uniqueHistory=[];
function player(name){return{name,reflexBest:null,reflexTries:0,tapBest:{},tapTries:{},uniquePoints:0,uniqueWins:0,state:'standby',visible:true,lastSeen:Date.now()}}
const clean=v=>String(v||'').trim().slice(0,20)||'名無し';
function byName(name){const k=clean(name).toLowerCase();for(const[id,p]of players)if(p.name.toLowerCase()===k)return[id,p];return null}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data))}
function read(req){return new Promise(ok=>{let b='';req.on('data',c=>b+=c);req.on('end',()=>{try{ok(JSON.parse(b||'{}'))}catch{ok({})}});req.on('error',()=>ok({}))})}
function sse(res,event,data){try{res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`)}catch{}}
const emitPlayers=(e,d)=>{for(const r of playerStreams.values())sse(r,e,d)},emitHosts=(e,d)=>{for(const r of hostStreams)sse(r,e,d)};
function rank(rows){let previous=null,previousRank=0;return rows.map((x,i)=>{const r=previous!==null&&x.score===previous?previousRank:i+1;previous=x.score;previousRank=r;return{...x,rank:r}})}
function leaderboard(){if(view.mode==='unique')return rank([...players.values()].map(p=>({name:p.name,score:p.uniquePoints,tries:p.uniqueWins})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score));if(view.mode==='tap'){const k=String(view.duration);return rank([...players.values()].map(p=>({name:p.name,score:p.tapBest[k],tries:p.tapTries[k]||0})).filter(x=>Number.isFinite(x.score)).sort((a,b)=>b.score-a.score))}return rank([...players.values()].filter(p=>Number.isFinite(p.reflexBest)).map(p=>({name:p.name,score:p.reflexBest,tries:p.reflexTries})).sort((a,b)=>a.score-b.score))}
function booby(board){if(view.mode==='unique'||board.length<2)return{prize:[],maker:[]};const scores=[...new Set(board.map(x=>x.score))];if(scores.length<2)return{prize:[],maker:board.map(x=>x.name)};return{prize:board.filter(x=>x.score===scores.at(-2)).map(x=>x.name),maker:board.filter(x=>x.score===scores.at(-1)).map(x=>x.name)}}
const label=s=>({countdown:'カウントダウン',ready:'反射待機',playing:'プレイ中',result:'結果表示',answering:'回答中',closed:'締切待機'})[s]||s||'未確認';
function presence(){const now=Date.now(),detail=[];let standby=0,connected=0,playing=0;for(const[id,p]of players){const online=playerStreams.has(id)&&now-p.lastSeen<30000;if(online)connected++;if(online&&p.visible&&p.state==='standby')standby++;else{if(online&&['countdown','ready','playing','answering','result','closed'].includes(p.state))playing++;detail.push({name:p.name,state:!online?'切断・未確認':!p.visible?'画面非表示':label(p.state)})}}return{connected,standby,playing,notStandby:players.size-standby,detail}}
function stats(){return{joined:players.size,answered:view.mode==='unique'?uniqueGame.answers.size:leaderboard().length,round:round.id,active:round.active,activeMode:round.mode,mode:view.mode,duration:view.duration,practice:round.practice,roundCompleted:roundResponses.size,uniqueStatus:uniqueGame.status,generation,...presence()}}
function payload(){const b=leaderboard();return{board:b,stats:stats(),booby:booby(b),uniqueResult:uniqueGame.result,uniqueHistory}}
function push(){emitHosts('leaderboard',payload())}
function valid(b){return b&&b.sessionGeneration===generation&&players.has(String(b.id||''))}
function setState(id,state,visible){const p=players.get(id);if(!p)return;p.state=String(state||p.state);p.visible=visible!==false;p.lastSeen=Date.now()}
function finishIfAll(){if(players.size&&roundResponses.size>=players.size)round.active=false}
function evaluateUnique(){const counts=new Map();for(const n of uniqueGame.answers.values())counts.set(n,(counts.get(n)||0)+1);const uniqueNumbers=[...counts].filter(([,c])=>c===1).map(([n])=>n).sort((a,b)=>b-a),winningNumber=uniqueNumbers[0]??null,winners=[];if(winningNumber!==null){for(const[id,n]of uniqueGame.answers)if(n===winningNumber){const p=players.get(id);if(p){winners.push(p.name);if(!uniqueGame.practice){p.uniquePoints++;p.uniqueWins++}}}}const podium=uniqueNumbers.slice(0,3).map((number,index)=>{let name='';for(const[id,answer]of uniqueGame.answers){if(answer===number){const p=players.get(id);name=p?p.name:'';break}}return{place:index+1,number,name}});const result={historyId:uid(),roundId:round.id,roundNumber:uniqueHistory.length+1,winningNumber,winners,podium,answerCount:uniqueGame.answers.size,distribution:[...counts].sort((a,b)=>a[0]-b[0]).map(([number,count])=>({number,count,unique:count===1,winner:number===winningNumber})),practice:uniqueGame.practice};uniqueGame.result=result;uniqueGame.status='revealed';round.active=false;if(!uniqueGame.practice)uniqueHistory.push(result);return result}
function serve(res,file){fs.readFile(file,(e,d)=>{if(e){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});res.end(d)})}
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`),p=u.pathname;if(p==='/healthz')return json(res,200,{ok:true});if(p==='/'||p==='/player')return serve(res,path.join(PUBLIC,'player.html'));if(p==='/host')return serve(res,path.join(PUBLIC,'host.html'));
if(p==='/events/player'){const id=u.searchParams.get('id');if(u.searchParams.get('generation')!==generation)return json(res,409,{staleSession:true});if(!players.has(id))return json(res,404,{playerMissing:true});res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-store',Connection:'keep-alive','X-Accel-Buffering':'no'});res.write('\n');const old=playerStreams.get(id);if(old&&old!==res)try{old.end()}catch{}playerStreams.set(id,res);setState(id,'standby',true);sse(res,'hello',{round,generation});push();req.on('close',()=>{if(playerStreams.get(id)===res)playerStreams.delete(id);push()});return}
if(p==='/events/host'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-store',Connection:'keep-alive','X-Accel-Buffering':'no'});res.write('\n');hostStreams.add(res);sse(res,'leaderboard',payload());req.on('close',()=>hostStreams.delete(res));return}
if(req.method==='POST'&&p==='/api/join'){const b=await read(req),name=clean(b.name),old=byName(name);if(old)return json(res,200,{id:old[0],name:old[1].name,sessionGeneration:generation,round});const id=uid();players.set(id,player(name));push();return json(res,200,{id,name,sessionGeneration:generation,round})}
if(req.method==='POST'&&p==='/api/rejoin'){const b=await read(req),id=String(b.id||'');if(b.sessionGeneration!==generation)return json(res,409,{staleSession:true});if(!players.has(id))return json(res,404,{playerMissing:true});setState(id,'standby',true);return json(res,200,{id,name:players.get(id).name,sessionGeneration:generation,round})}
if(req.method==='POST'&&p==='/api/state'){const b=await read(req);if(!valid(b))return json(res,409,{staleSession:true});setState(String(b.id),b.state,b.visible);push();return json(res,200,{ok:true})}
if(req.method==='POST'&&p==='/api/select-ranking'){const b=await read(req);view.mode=['reflex','tap','unique'].includes(b.mode)?b.mode:'reflex';view.duration=[5,7,10].includes(Number(b.duration))?Number(b.duration):7;push();return json(res,200,payload())}
if(req.method==='POST'&&p==='/api/start'){const b=await read(req),mode=b.mode==='tap'?'tap':'reflex',duration=[5,7,10].includes(Number(b.duration))?Number(b.duration):7;round={id:round.id+1,active:true,mode,duration,practice:Boolean(b.practice)};view={mode,duration};roundResponses=new Set();emitPlayers(mode==='tap'?'tap-start':'reflex-start',{roundId:round.id,duration,practice:round.practice,countdown:3,generation});push();return json(res,200,{ok:true,round})}
if(req.method==='POST'&&p==='/api/result'){const b=await read(req);if(!valid(b))return json(res,409,{staleSession:true});if(Number(b.roundId)!==round.id)return json(res,409,{oldRound:true});const id=String(b.id),pl=players.get(id);roundResponses.add(id);setState(id,'result',true);if(!round.practice){if(round.mode==='tap'&&Number.isFinite(Number(b.taps))){const k=String(round.duration),n=Math.max(0,Math.round(Number(b.taps)));if(!Number.isFinite(pl.tapBest[k])||n>pl.tapBest[k])pl.tapBest[k]=n;pl.tapTries[k]=(pl.tapTries[k]||0)+1}else if(round.mode==='reflex'&&!b.foul&&Number.isFinite(Number(b.timeMs))&&Number(b.timeMs)>0){const n=Math.round(Number(b.timeMs));if(!Number.isFinite(pl.reflexBest)||n<pl.reflexBest)pl.reflexBest=n;pl.reflexTries++}}finishIfAll();push();return json(res,200,{ok:true})}
if(req.method==='POST'&&p==='/api/unique'){const b=await read(req);if(b.action==='open'){if(uniqueGame.status==='open')return json(res,409,{alreadyOpen:true});round={id:round.id+1,active:true,mode:'unique',duration:0,practice:Boolean(b.practice)};view={mode:'unique',duration:0};roundResponses=new Set();uniqueGame={status:'open',answers:new Map(),result:null,practice:round.practice};emitPlayers('unique-open',{roundId:round.id,practice:round.practice,generation});push();return json(res,200,{ok:true})}if(b.action==='close'){if(uniqueGame.status!=='open')return json(res,409,{wrongState:true});uniqueGame.status='closed';emitPlayers('unique-closed',{});push();return json(res,200,{ok:true})}if(b.action==='reveal'){if(uniqueGame.status!=='closed')return json(res,409,{wrongState:true});const result=evaluateUnique();emitPlayers('unique-result',result);push();return json(res,200,{ok:true,result})}return json(res,400,{ok:false})}
if(req.method==='POST'&&p==='/api/unique-answer'){const b=await read(req);if(!valid(b))return json(res,409,{staleSession:true});if(uniqueGame.status!=='open')return json(res,409,{closed:true});const n=parseInt(b.number,10);if(!(n>=1&&n<=100))return json(res,400,{invalidNumber:true});uniqueGame.answers.set(String(b.id),n);roundResponses.add(String(b.id));setState(String(b.id),'answering',true);push();return json(res,200,{ok:true,number:n})}
if(req.method==='POST'&&p==='/api/reset'){for(const pl of players.values()){pl.reflexBest=null;pl.reflexTries=0;pl.tapBest={};pl.tapTries={};pl.uniquePoints=0;pl.uniqueWins=0}round.active=false;roundResponses=new Set();uniqueGame={status:'idle',answers:new Map(),result:null,practice:false};uniqueHistory=[];emitPlayers('reset',{});push();return json(res,200,{ok:true})}
if(req.method==='POST'&&p==='/api/reset-all'){emitPlayers('kick',{});for(const r of playerStreams.values())try{r.end()}catch{}playerStreams.clear();players.clear();generation=uid();round={id:0,active:false,mode:'reflex',duration:7,practice:false};view={mode:'reflex',duration:7};roundResponses=new Set();uniqueGame={status:'idle',answers:new Map(),result:null,practice:false};uniqueHistory=[];push();return json(res,200,{ok:true})}res.writeHead(404);res.end('Not found')});
setInterval(push,10000).unref();server.listen(PORT,'0.0.0.0',()=>console.log(`Halloween party game server on ${PORT}`));
